### PR TITLE
add RDS log file commands

### PR DESCRIPTION
**Pull request by ryanbarry**
had the need to programmatically access log files today, didn't see the endpoints in the script so i did my best to follow conventions i saw and add them.

i'm unsure about the short names i chose for the commands and parameters, so i'm definitely open to feedback there

### CODE REVIEW

**Comment by timkay** [comment]
Ryan, sounds good. Please see if you can make the commands match http://docs.aws.amazon.com/AmazonRDS/latest/CommandLineReference/command-reference.html

**Comment by ryanbarry** [comment]
i thought they matched pretty well, only differences i note in looking back over the docs is that i've added the extra params available via the API to `describe-db-log-files` vs the CLI, but i assume that's OK, right? is there anything else i'm missing?

**Comment by ryanbarry** [comment]
though, the CLI command doesn't exactly correspond to the API, so should i make a command that mirrors the CLI in addition to the one that exposes the API more directly?

**Comment by timkay** [comment]
I misunderstood from your original post when you said you didn't know if you named them right. However, you now indicate that you did a pretty good job. I'll go ahead and merge. Thanks!

**Pull request merged**
